### ISSUE TITLE
Not all taxon names are found using the search box.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonpages#193]
Taxon names without OTU are not found on TaxonPages. I have most of the combinations without OTUs. When I search for a combination name, the system return no resuts. I got complains from users, that they cannon find taxa they are looking for. An example: 'Limotettix anthracinus'.

**Comment by mjy** [comment]
If you make an OTU for that taxon does it work?

**Comment by proceps** [comment]
I cannot make OTUs for all combination, this will significantly complicate the editing process.

**Comment by mjy** [comment]
Since there is no OTU with that combination name we can't show it in the list without a major refactor, and keeping priority across this is hard.  I can tweak it to find the target protonym at least:

<img width="686" alt="Screenshot 2023-12-06 at 3 31 05 PM" src="https://github.com/SpeciesFileGroup/taxonpages/assets/22600/1933502a-da5c-4036-b4ce-c61c34e9ab08">

In addition, that string isn't in the system to start with, it's in a subgenus format, so even if we do tweak the user still won't see the exact string they looked for.  So, this is tricky, and I'm not sure worth the refactor at this point?  Exploring a little with `anthracinus` by itself will let you find it in the synonym list.

**Comment by mjy** [comment]
Pedantically: 'Empoasca vitis" -> 'Empoasca vitium' (so not an exact match), and it took me 30 seconds to find "Delphacodes hyas" by dropping to search for "hyas".  I do understand that we can do better.

**Comment by proceps** [comment]
This is getting critical, I getting more complains that the names are not found on the TaxonPages. Today I got a request for "Stirellus indrus" which is present in TW, but not found using TP interface.

**Comment by LocoDelAssembly** [comment]
If this has to do with the `having_taxon_name_only=true`  option (which means only OTUs with `Otu.name=nil`), please do not disable globally @jlpereira (at least not initially), do only for hoppers.

**Comment by mjy** [comment]
@proceps Please inspect the JSON and play with the parameters as @LocoDelAssembly notes, if you can find a parameterized solution we can adopt that, but see my commnet on OTUs being the problem above.

**Comment by proceps** [comment]
I have no OTUs on subsequent combination. This is intentional. Now I can search only by original combination and current combination.

**Comment by proceps** [comment]
having_taxon_name_only means that OTU exists, but the name field is blank

**Comment by mjy** [comment]
@proceps Please add a failing spec or two (change `specify` to `xspecify` after you get the spec in place and working) to `spec/lib/queries/otu/autocomplete.rb`, we're not going to make progress without that in place.

**Comment by proceps** [comment]
added a spec test
