### ISSUE TITLE
Nomenclature references: Add link to url

### ISSUE THREAD

**Issue by jlpereira** [SpeciesFileGroup/taxonpages#73]
Endpoint: `/api/v1/taxon_names/<id>/inventory/catalog`

We have to add an hyperlink for  the source url

**Comment by mjy** [comment]
I think we will do this as a seperate attribute so that you can link the whole source.  Injecting it just on the URL is a lot of overhead on the standard libraries we use.

MVPs should answer questions that otherwise can't be answered rather than add bonus functionality.   Technically the question can be answered as currently presented when the URL is visible.

**Comment by jlpereira** [comment]
Sounds good to me. If you add an attribute with the URL I could inject it into the string
